### ISSUE TITLE
Destroy action does not work on VMware Fusion 5.0.2

### ISSUE THREAD

**Issue by jasonberanek** [jedi4ever/veewee#511]
I've observed that destroying VMs with the VMware Fusion provider with the current head branch against VMware Fusion 5.0.2 Professional fails with the following error:

```
fission-0.4.0/lib/fission/metadata.rb:88:in `delete_vm_favorite_entry': undefined method `delete_if' for nil:NilClass (NoMethodError)
    from fission-0.4.0/lib/fission/metadata.rb:27:in `delete_vm_info'
    from fission-0.4.0/lib/fission/vm.rb:675:in `delete'
    from veewee/lib/veewee/provider/vmfusion/box/destroy.rb:12:in `destroy'
```

The error appears because the [fission](http://github.com/thbishop/fission) library does not support VMware Fusion 5. From looking at the fission code, it appears that the properties list for Fusion changed between version 4 and 5 causing the above code to fail. The files for the VM are deleted from the machine, but the name of the VM persists in the Fusion Virtual Machine Library view until it is deleted by a user. Ideally, this issue should be addressed in fission (see thbishop/fission#23), but capturing it here in case veewee should monkey patch the behavior in the interim.

From my testing, the rest of the commands for the Fusion provider work as expected.
